### ISSUE TITLE
if a <a> link is clicked the hash part is add twice

### ISSUE THREAD

**Issue by frozeman** [visionmedia/page.js#101]
something like this will happen then:
    http://localhost/keep-your-light-shining#live#live

When using `page()` everything seem to work fine

**Comment by denevell** [comment]
What's the href on the a link? #204 made me realize I need to put /link and not #!/link

**Comment by matthewp** [comment]
Hey! This was recently fixed and should no longer be an issue in 1.8.0. Let me know if you discover otherwise.
