### ISSUE TITLE
cdnjs.cloudflare.com?

### ISSUE THREAD

**Issue by DylanPiercey** [visionmedia/page.js#120]
Is it possible to get this repo on the cdn?

**Comment by jcoffland** [comment]
I tried to do this here: https://github.com/cdnjs/cdnjs/pull/4597.  Unfortunately my PR failed testing.  Anyone know how to do this the right way?

**Comment by jcoffland** [comment]
You could add a mention in the docs and close this ticket.  I got page.js on cdnjs.  See: https://cdnjs.com/libraries/page.js

If I did it right it should autoupdate when the next version is released.
