### ISSUE TITLE
refactor for multiple Page instances

### ISSUE THREAD

**Issue by tj** [visionmedia/page.js#13]
Multiple `Page` objects could be used with basepaths and operate independently, but the existing API will be left as-is, this would make testing a bit easier since the routes would reset etc...

**Comment by matthewp** [comment]
API I am thinking of is:

```js
var newPage = page.create(options);

// You can also pass options this way
newPage.configure(options);

newPage('/', function(){

});

newPage.redirect('/foo', '/bar');

newPage.start();
```

**Comment by paulocoghi** [comment]
@matthewp , very good!
