### ISSUE TITLE
Idea: page.back()

### ISSUE THREAD

**Issue by rstacruz** [visionmedia/page.js#157]
page.back() will be the equivalent of running `if (there's history to go back to) { history.back() }`.

``` js
page.back()
```

Optionally, you should be able to pass a path to fall back on, in case you're trying to do `page.back()` on the first page.

``` js
page.back('/dashboard')
```

To do this, we'll need to track history length on `Context#pushState`.

``` js
page.length == 0
page('/another/page')
page.length == 1
```

I have this implemented in https://github.com/rstacruz/repage.js — happy to merge the implementation here if you're all happy with the feature and the api. thoughts?

**Comment by hems** [comment]
for some weird reason, page.back() and history.back() doesn't work on my application running on chrome.

the URL changes but the route isn't triggered again

**Comment by cabhishek** [comment]
@hems Did you figure out the issue with page.back() + chrome ?

**Comment by Nomia** [comment]
@hems Same problem here, did u figure that out?

**Comment by hems** [comment]
@Nomia yeah, stopped using page.js!

Used https://github.com/arboleya/ways instead

**Comment by Nomia** [comment]
thx, I'll give it a try @hems
