### ISSUE TITLE
Routing will fail if history.pushState is not supported.

### ISSUE THREAD

**Issue by stevemckenzie** [visionmedia/page.js#179]
You would think that at the end of 2014, all modern browsers would support it across the board but unfortunately, I just discovered that Firefox Addons do not. Chrome extensions do though.

So with that said, the site we are currently trying to display via a Firefox Addon iframe ends up not displaying because of this issue.

The specific line that is causing this for my case is:
https://github.com/visionmedia/page.js/blob/master/page.js#L315

I was trying to setup falling back to hashbangs using the options you can pass at start, but once I read the code more, it seems like everything always goes through the context saving and doing this was not working.

Using `if ('history' in window && 'pushState' in history) {` was properly catching that pushState is not usable in an addon.

Any thoughts on a quick solution?

**Comment by matthewp** [comment]
Yep, what @kethinov said. Closing.
