### ISSUE TITLE
Run on server

### ISSUE THREAD

**Issue by skellyb** [visionmedia/page.js#191]
I'm using page.js to handle routing in a React.js component. Works great in the browser, love the simple approach. Now I'd like to render the component on the server, but not surprising, the missing `window` variable in page.js crashes things right away:
```
var location = window.history.location || window.location;
```

On the server I just need this work in its most basic form. Pass a path into `page(path)` and the route's callback fires. Any advice? Should I just isolate page.js to the browser, and run the routes through something else on the server, basically a paired down version of page.js for the server?

Thanks!

**Comment by charypar** [comment]
@skellyb I'm looking into your use-case just now. Did you get anywhere? 

What I plan to do is use the Route class directly to create the list of route definitions and then walk through them to do the path resolution. I'll post a code sample if I get it to work.

**Comment by skellyb** [comment]
Hi @charypar, this probably doesn't help you, but I ended up putting a small wrapper around page.js, preventing it from running at all on the server. I figured much of what page.js is doing is browser specific, so I use `route-builder` to parse the path and call the appropriate callback.

Similar to this:
```
var MyRouter = function(routes) {
    var base = '';

    if (Environment.canUseDOM) {
        // Browser Router
        var page = require('page');
        page.base(base);

        Object.keys(routes).forEach(function(key) {
            page(key, routes[key]);
        });

        this.go = page;
    } else {
        // Server Router
        var RouteBuilder = require('route-builder');

        var serverRoutes = Object.keys(routes).map(function(key) {
            return ['route'+key, key, routes[key]];
        });

        var router = RouteBuilder(serverRoutes);

        this.go = function(path) {
            var match = router.match( path.replace(base, '') );
            if (match) match.meta(match);
        };
    }
};
```

Thanks for looking at this. Page.js is working great for me in the browser.

**Comment by charypar** [comment]
Hey @skellyb. I ended up using the internals, as mentioned above. We already have a wrapper around Page.js because we have a more constrained use-case than a general callback, but essentially, for server side routing, we're defining routes using something like 

```livescript
page: (pattern, component) ->
  route: new page.Route pattern
  component: component-class
```

and collecting the results in an array. Matching the routes and binding the named parameters then looks like this:

```livescript
resolve: (url, routes) ->
  params = []
  route = routes |> find -> it.route.match url, params

  return [null] unless route

  [route.component, params]
```

Sorry the code samples are in [LiveScript](http://livescript.net), hope it makes sense anyway.

**Comment by duereg** [comment]
Maybe you should try something like [this package](https://github.com/kethinov/page.js-express-mapper.js) to solve the issue?
