### ISSUE TITLE
Do a new release of page.js

### ISSUE THREAD

**Issue by samccone** [visionmedia/page.js#200]
There has been 40~ commits since the last release of page.js. Some of the commits are quite important to a functioning router. 

Would you consider releasing 1.6 of this tool so i do not have to refer to a SHA off of master?
Thanks for much for this great tool. :heart:

**Comment by rstacruz** [comment]
merged. shall we?

**Comment by shuvalov-anton** [comment]
@rstacruz @samccone Yes. I'm sorry for dalay. I'm going to release just now

**Comment by shuvalov-anton** [comment]
yay! I've published [`1.6.0`](https://github.com/visionmedia/page.js/releases/tag/1.6.0) at last :D

**Comment by rstacruz** [comment]
:heart:

**Comment by samccone** [comment]
:heart: :heart:
