### ISSUE TITLE
ctx.params is an Array with properties, so it cannot be serialized with JSON.stringify.

### ISSUE THREAD

**Issue by jesseskinner** [visionmedia/page.js#203]
The params are not serializable with `JSON.stringify()`, because they get turned into an empty array and the object properties are lost.

For example, if I have named parameters, like so:

```javascript
page('/page/:id', function(ctx) {
    console.log(ctx.params, JSON.stringify(ctx.params));
});
```

then the result in the console will be like this:

```javascript
[id: "123"] "[]"
```

Currently I have to do a workaround and copy the parameters over to a normal object before serialization. This works, but having a normal object with named parameters would be cleaner.

For backwards compatibility, since some people are probably assuming `ctx.params` is an array, maybe there needs to be an additional parameter on `ctx` that contains an object with only the named parameters, like `ctx.namedParams`, that is safe to be serialized?

**Comment by shuvalov-anton** [comment]
Hm.. I'm thinking about to use `object` instead `array` for ctx.params. Need to look does [this conditional][1] is working.

[1]: https://github.com/visionmedia/page.js/blob/master/index.js#L451

**Comment by shuvalov-anton** [comment]
Looks like the conditional is not working because of [`path-to-regexp`][1] always returns array of the keys with `key.name`. I'm going to replace `params` with `object`. It's should resolve the problem.

[1]: https://github.com/pillarjs/path-to-regexp

**Comment by jesseskinner** [comment]
Fantastic, thanks so much for the quick solution!

**Comment by shuvalov-anton** [comment]
@jesseskinner Is it work for you? :D If it is, then I'm going to merge the PR into the master.

**Comment by jesseskinner** [comment]
@shuvalov-anton Yep, that did the trick. Thanks again!
