### ISSUE TITLE
this can't back

### ISSUE THREAD

**Issue by cloudAi** [visionmedia/page.js#207]
http://localhost:4000/basic/#whoop

**Comment by cloudAi** [comment]
http://localhost:4000  goto   http://localhost:4000/basic/#whoop  and then can't back http://localhost:4000

**Comment by rstacruz** [comment]
if that's what you're after, maybe `history.go(-1)` would work for you. `page.back()` will only work on states that page.js has navigated to.

**Comment by matthewp** [comment]
I think @rstacruz has answered this well enough!
