### ISSUE TITLE
Lib size really ~1200 bytes?!

### ISSUE THREAD

**Issue by analog-nico** [visionmedia/page.js#208]
I just pasted the code into http://closure-compiler.appspot.com/home with advanced optimization and got "2.42KB gzipped". Is the 1200 bytes statement incorrect or do you use some particular compression that gets it down to 1200 bytes?

**Comment by EngineeringMode** [comment]
Wow, I got the same thing. Is the 1,200 byte quote just really out of date?

**Comment by shuvalov-anton** [comment]
Yes it is. Good catch :D

**Comment by pavel** [comment]
http://visionmedia.github.io/page.js/ still says ~1200 bytes.

**Comment by t829702** [comment]
> http://visionmedia.github.io/page.js/ still says ~1200 bytes.

got here in 2021, still there? /cc @A
