### ISSUE TITLE
Hashbang routing does not work with file protocol

### ISSUE THREAD

**Issue by liammclennan** [visionmedia/page.js#209]
If I load file:///C:/work/index.html page.js sets the url to 

```
file:///C:/work/index.html#!/C:/work/StudyNotes/src/www/index.html
```

which makes the routes wrong. The file protocol is important because it enables page.js to be used with things like Apache Cordova.

**Comment by criesbeck** [comment]
Just ran into this also, though outside Cordova. Would simply adding "#!" to the file URL you call in Cordova fix this for your purposes?

**Comment by liammclennan** [comment]
I don't think so. The page('') function used to trigger routes sets the hash fragment incorrectly.

**Comment by criesbeck** [comment]
Not following, I'm afraid. The [line of code](https://github.com/visionmedia/page.js/blob/master/page.js#L160)  that creates the URL first searches for #!. If it finds it, it uses whatever follows, so if your URL ends with #! it will append just the empty string. Only if #! is not found does it make the doubled URL.  I have a test toy HTML file that does page({ hashbang: true }) and gets the undesired effect when I open page-test.html but not when I open page-test-html#!

**Comment by liammclennan** [comment]
Sorry. I don't have a test page available to try it.

**Comment by criesbeck** [comment]
What about editing the content element's src in config.xml to say "index.html#!" instead of index.html?

**Comment by liammclennan** [comment]
That might work, but I don't have an application with which to test it.

On Fri, Jan 23, 2015 at 11:07 PM, Chris Riesbeck <notifications@github.com>
wrote:

> What about editing the content element's src in config.xml to say
> "index.html#!" instead of index.html?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/visionmedia/page.js/issues/209#issuecomment-71190599>.
>



-- 
Liam McLennan.

liam@eclipsewebsolutions.com.au
http://www.eclipsewebsolutions.com.au

**Comment by matthewp** [comment]
I was able to get a file protocol example working with hashbang when using `page.base(location.pathname);`. This makes everything just work. So I think the underlying problem is, when we are using hashbang we need to make sure to treat everything as though the base === location.pathname.
