### ISSUE TITLE
escaping from base bug

### ISSUE THREAD

**Issue by ivankravchenko** [visionmedia/page.js#211]
I have trouble with using base and external links.
For better understanding I've assembled [example](https://github.com/SE7ENSKY/page.js/commit/c8ed94c5f3e6de29c94c0e55f028f78a539bbd9e).
Foo and bar links are ok, but external foo isn't meant to be captured by page.js.
Notice same URL part – escape-from-base.

[Live website](http://fedoriv.com/hub/) with this case with language selector not working.

**Comment by shuvalov-anton** [comment]
@ivankravchenko thank you for example

**Comment by matthewp** [comment]
This doesn't appear to be an issue any more. Closing.

![screen shot 2018-01-18 at 6 48 55 am](https://user-images.githubusercontent.com/361671/35096839-aa1d1e78-fc1b-11e7-9e98-e6fef20553ec.png)
