### ISSUE TITLE
Popstate fired on initial page load causes double trigger (Safari 8)

### ISSUE THREAD

**Issue by iamcarbon** [visionmedia/page.js#213]
Safari 8 is still firing a popstate event after the page is ready. This causes a second match to occur and triggers the current route to exit and return. Chrome, IE, and Firefox are all OK.

Should a check to ignore the initial stateless popstate in Safari be added?

**Comment by asabhaney** [comment]
+1

**Comment by uiureo** [comment]
+1

I ran into this problem when I use phantomjs in e2e testing.

**Comment by sheepsteak** [comment]
+1

**Comment by orenf** [comment]
+1

**Comment by bendik** [comment]
+1

**Comment by markkemper1** [comment]
Yes

**Comment by hishayness** [comment]
+1

**Comment by pr1ntr** [comment]
+1 ??

**Comment by jackyon** [comment]
+1

**Comment by shuvalov-anton** [comment]
pull requests are welcome

**Comment by kethinov** [comment]
This should solve it: https://github.com/visionmedia/page.js/pull/239

**Comment by shuvalov-anton** [comment]
It's time to release new version, I think :tada:

**Comment by kethinov** [comment]
:+1:

**Comment by alekseykulikov** [comment]
Is is a time to release this fix? ;)

**Comment by shuvalov-anton** [comment]
@alekseykulikov yep, but I'm going to merge #243 before release.
