### ISSUE TITLE
change global variable to something else

### ISSUE THREAD

**Issue by timothyerwin** [visionmedia/page.js#214]
I think page is too common of a name for this library. I want to use page as a local variable and this conflicts. I know I can reassign the name myself, but I think it would be nice if a different default global name is chosen.

router, vm.router, ???

**Comment by shuvalov-anton** [comment]
-1 from me. if you want to use page as a local variable and avoid global variables collision, you should use  it with [browserify][1] or [component][2].

[1]: https://github.com/substack/node-browserify
[2]: https://github.com/componentjs/component

**Comment by timothyerwin** [comment]
yes, because all the users should have to go through extra effort to avoid collision with one of the most blatantly common variable names you could imagine.

**Comment by shuvalov-anton** [comment]
Collision of the globals is a problem of bad app design. It's not a problem of page.js.  `window.page` should be nice in simple project, but in large projects you need to look for another solutions like browserify.

**Comment by timothyerwin** [comment]
it couldn't possibly be a problem of bad global variable design?

**Comment by shuvalov-anton** [comment]
Hah ;D mb, but you can't go to all "bad global variable design" projects and ask to rename their globals. What if somewho is using `router` variable too?

**Comment by timothyerwin** [comment]
well, given that page.js _is_ a router, I assume it's much more realistic. but maybe that's why libraries have names like angular, react, riot, express, etc.

so, I think this is modeled off express.js (same author, no?), and it in fact has a class called Router to handle this server side, but it's namespaced under express:

```javascript
var express = require('express');
var router = express.Router();

router.get('*', function(req, res){
  res.sendfile(path.resolve('public/index.html'));
});

module.exports = router;
````

so, I know there is also a library called superagent (good global name) that handles ajax calls...perhaps they could all get namespaced under a common browser framework like express? just an idea.

also this isn't a HUGE issue...I've sidestepped it, and as you mentioned there are workarounds. just a suggestion.

**Comment by shuvalov-anton** [comment]
Are you honestly have this problem with the globals? Can you show me your case?

**Comment by timothyerwin** [comment]
yes, I have a local variable called `page`, which I'm actually using in conjunction with page.js, since it's a natural use case in a single page app to load a page from the router.

once you define a local variable of `page` to reference your own page it overshadows the global page variable. I'm sure you can get back to it with `window.page` or in another case I just use `p` for my local variable...it's just a hassle to workaround what I think is a natural local variable anyone might use along with this library.

so the pseudo code is like this:

````javascript

page('/faq', function(e){
   self.load(e);
});

self.load = function(e){
  var page = $('<article/>');

  $('#pages').append(page);

  page.load(e);
});

**Comment by timothyerwin** [comment]
if this were part of a client framework, lets just call it `coco.js` for now...

```javascript
coco.router.on('/faq', function(e){
   self.load(e);
};

self.load = function(e){
 var page = $('<article/>');

 $('#pages').append(page);

 page.load(e + '.html');
};
````

imo, that's much simpler and easier to understand.

**Comment by shuvalov-anton** [comment]
My favorite way :D 

```js
self.load = function(e){
  $('<article/>')
    .append(page)
    .load(e + '.html')
  ;
};
```

**Comment by timothyerwin** [comment]
did you mean:

````javascript
self.load = function(e){
  $('<article/>')
    .appendTo('#pages')
    .load(e + '.html');
};
````

that's all cool if you only care about simple appending and don't need to do other work with the page variable. there are workarounds here and there, but I think I've made a good case against the global name.

**Comment by rstacruz** [comment]
:-1:.  people already use this library as `page`, and these kinds of issues are trivial enough that it's easily sidestepped. and as @shuvalov-anton mentioned, a setup with browserify/component would be ideal (for many reasons) and would avoid this issue altogether.


```js
var nav = window.page;

function load(e) {
  var page = $('<article/>');
  $('#pages').append(page);
  page.load(e);
  nav('/foo');
});
```

**Comment by timothyerwin** [comment]
I'm using it through bower. how would I do it via browserify and how would that solve this?

**Comment by supermensa** [comment]
@timothyerwin
How about just simply doing either passing in router to an anonymous function

```
(function(router){
  router('/foo')
}(window.page)
```

or assign page to another variable,
delete the reference and set your own

```
window.router = window.page;
delete window.page;
window.page = function foobar(){ /* ... */ }
```
