### ISSUE TITLE
Need path-to-regexp when using CDN or browserify

### ISSUE THREAD

**Issue by jcoffland** [visionmedia/page.js#217]
I cannot get version 1.6.0 to work with out manually copying in ```path-to-regexp.js```.  This should at least be documented.

Great project by the way.

**Comment by shuvalov-anton** [comment]
Strange. How you install this module for browserify? `npm`, yep?

**Comment by jcoffland** [comment]
I just copied the Javascript file into my project.

**Comment by shuvalov-anton** [comment]
ah, I get it. You must use `npm install page` in you project dir. That command will fetch `page` from `npm` and install all dependencies it needed. But what's wrong with CDN?

**Comment by shuvalov-anton** [comment]
Try to use [compiled verison][1] without browserify.

[1]: https://github.com/visionmedia/page.js/blob/master/page.js

**Comment by jcoffland** [comment]
I'm using the npm version now.  I think CDN is fine.  I made a mistake there. Thanks.
