### ISSUE TITLE
Back button does not work with hash links in Firefox

### ISSUE THREAD

**Issue by jcoffland** [visionmedia/page.js#218]
If you click a hash link (e.g. ```/home#something```) Firefox's back button fails to work.  Here is a fiddle that demonstrates the bug:

  http://jsfiddle.net/oz97q94o/

Also, note that in the browser's history there are two entries for the hash link whereas a normal link only adds one entry to the history.  I think this is why it fails to go back.  When you hit the back button it removes one history entry but you still end up on the same page because of the double entry.  Then page.js triggers another entry which puts you back to two again.  So you can't go back.

FYI, I also tested this in Chrome and the back button works fine there.

**Comment by shuvalov-anton** [comment]
I think, this issue should be closed
