### ISSUE TITLE
Warning when use in webpack

### ISSUE THREAD

**Issue by Makio64** [visionmedia/page.js#225]
Hi guys,

There is a warning coming from webpack when using page.js because it's actually bundle by browserify.

I forked and push a version of the script wihout using browserify to create page.js witch works fine and respect the amd standard:
https://github.com/Makio64/page.js/blob/master/page.js

Because Page.js can be use in many cases, it will be nice to not bundle it automatically with browserify.

Cheers!

**Comment by shuvalov-anton** [comment]
Hi! Probably it's webpack's problem webpack/webpack#319
