### ISSUE TITLE
onclick handler fails to ignore links that contain (but dont start with) the base url

### ISSUE THREAD

**Issue by spudly** [visionmedia/page.js#234]
If a link does not starts with the baseUrl, it should be ignored by the onclick handler and should continue to have their native behavior.

Any link whose pathname contains (not starts-with) the base url will fail to be ignored by the onClick handler. As a result, links that should actually go to a different page are triggering page.js routes instead.

For example, if my app has a base url of "/b", the link below should be ignored by the onClick handler, and the native behavior (opening that url) should be preserved:
```html
<a href="/a/b/c.html">Some File</a>
```

But instead, the onclick handler prevents the default action and calls `page.show('/a/b/c.html')`

I'll submit a pull request...

**Comment by codinfox** [comment]
Please update the documentation as well.

**Comment by jamrizzi** [comment]
Wow, I completely disagree with this. At the very least, you should have the option to not use it that way. With this current setup, if someone decides to change the base, you have to go through your entire codebase to change it. That's nasty and super not cool.

**Comment by jamrizzi** [comment]
Just did a pull request to fix this. https://github.com/visionmedia/page.js/pull/418
