### ISSUE TITLE
Going to root url when hashbang is true, and you have something in location.pathname, duplicates pathname

### ISSUE THREAD

**Issue by denevell** [visionmedia/page.js#242]
Say you have localhost/~myuser/path

And you have hashbang set to true

And then you go to  localhost/~myuser/path 

Then the url will be: http://localhost/~myuser/path/#!/~myuser/path/

This is because of:

```
var url = (hashbang && ~location.hash.indexOf('#!')) ? location.hash.substr(2) + location.search : location.pathname + location.search + location.hash;
```

It won't hit hashbang && ~location.hash.indexOf('#!') because there's no #! in the url. 

So it will hit the other, giving you /~myuser/somepath/

If you change the statement to:

```
if(hashbang && ~location.hash.indexOf('#!')) {
    url = location.hash.substr(2) + location.search; 
} else if (hashbang) {
    url = location.search + location.hash;
} else {
    url = location.pathname + location.search + location.hash;
}
```

Then the pathname isn't duplicated on going to the root.

I'll submit a CR with the above code when I've managed to get node running and run the tests etc. The above code is working fine for me at the moment, though.

**Comment by ronanpaixao** [comment]
Any idea on when this will be fixed? It's quite annoying and appears easy to fix.

**Comment by jstejada** [comment]
:+1:

**Comment by joeyroosing** [comment]
I tried the code provided by ronan, it indeed fixes the issue. When will this be released?

**Comment by Frikki** [comment]
But `#!` isn’t added to the path if hashbang is set to true.
