### ISSUE TITLE
Wildcards no longer work via path-to-regexp change (docs need updating?)

### ISSUE THREAD

**Issue by JonDum** [visionmedia/page.js#245]
I got burned hard today and had to go down the rabbit hole.

Updated from an older version of page.js and many of my routes weren't working.

I narrowed it down to routes like `page('/profile/*)` and `page('/login/*')`. Examples of this are all over the Page.js docs as valid ways of wildcard-matched routes. Yet, when pathToRegExp gets its claws on it, it spits out a regex like /^\/login\/**\***(?:\/(?=$))?$/i .... yea. That's an escaped asterisk literal.

Had to go digging around year-old closed issues to learn that this is [intended behavior by the author of path-to-regExp](https://github.com/pillarjs/path-to-regexp/issues/37). I was a bit surprised considering this was *at least* several months ago and page.js is still active.

So the question is, should the docs and usage be updated to reflect this change, or is this not ok by Page.js KISS standards and a solution needs to be found? If the former I can form a PR for doc changes.

**Comment by shuvalov-anton** [comment]
#115

**Comment by JonDum** [comment]
Ah don't know how I missed #115. Cheers I'll follow that one instead.
