### ISSUE TITLE
query.js bug

### ISSUE THREAD

**Issue by delgermurun** [visionmedia/page.js#248]
I know [query.js](https://github.com/visionmedia/page.js/blob/master/examples/query-string/query.js) used in example. But I use it and find a bug (I guess). Do you guys maintain it? If not, where is the repo?

Anyway here is the bug:
`qs.stringify({appId: 'new-i', hi: []});` returns `"appId=new-i&"`,

so `qs.parse('appId=new-i&');` returns `{appId: "new-i", "": ""}`,

so `qs.stringify({appId: "new-i", "": ""})` raising error.

I think `qs.stringify({appId: 'new-i', hi: []});` should be `"appId=new-i"`

EDIT: `qs.parse('appId=new-i&');` should be `{appId: "new-i"}`

**Comment by arunoda** [comment]
May be we can remove `&` if it comes at the end.

**Comment by delgermurun** [comment]
@arunoda `qs.stringify({appId: 'new-i', hi: [], hii: '', r1:''});` returns `"appId=new-i&&hii=&r1="`

**Comment by arunoda** [comment]
Oh!

**Comment by delgermurun** [comment]
I've found maintained version. That is https://github.com/hapijs/qs.
