### ISSUE TITLE
loaded check doesn't work if page.js is dynamically loaded

### ISSUE THREAD

**Issue by u9520107** [visionmedia/page.js#249]
I found that popstate detection was broken in my project, but found nothing in the issues.
After a bit of tracing code, I found that the error comes from this piece of code:

*index.js:235*
```javascript
  var onpopstate = (function() {
    var loaded = false;
      window.addEventListener('load', function() {
        setTimeout(function() {
          loaded = true;
        }, 0);
      });
   ... code omitted ...
  })();

```

Because my project would dynamically load in page.js after complete page load, this event listener would never be fired. Perhaps check document.readyState before setting up an event listener for this case?

**Comment by shuvalov-anton** [comment]
It's bad :( Yes, we need to check `readyState`. My fault, sorry
