### ISSUE TITLE
How to define "about:?" routes?

### ISSUE THREAD

**Issue by pke** [visionmedia/page.js#251]
I would like to define `about:config`, `about:libraries`, `about:blank` in my client app. How would I do that with page? So `about` is always required, everything else should be optional.

**Comment by shuvalov-anton** [comment]
`/about:item(.*)`. You can try it in [the `path-to-reegexp` playground][playground]

[playground]: http://forbeslindesay.github.io/express-route-tester/

**Comment by pke** [comment]
thanks. This does not seem to cover `about` and `about:`

Also I am running in a sandbox (Win8 Store App) and there history.pushState with "about" urls is not allowed for security reasons. Is there a way to prevent the Context of saving state? I'd monkey patch `Context.pushState` and `Context.save` as they are not needed in Single Page Windows Store Apps anyway.

**Comment by shuvalov-anton** [comment]
That covers. I don't know the way to disable `ctx.save` besides monkey patching :(

**Comment by pke** [comment]
Could we modify the route to when using `show("about:")` to set `context.params.item` to `""` instead of `":"`

**Comment by shuvalov-anton** [comment]
You can experiment with `path-to-regexp` on [the playground](http://forbeslindesay.github.io/express-route-tester/).
