### ISSUE TITLE
1.6.2 errors when required on the server

### ISSUE THREAD

**Issue by ryanatkn** [visionmedia/page.js#253]
In 1.6.1 you could `require('page')` outside of the browser environment without issue, but in 1.6.2 you get "document is not defined" on line 20 and "window is not defined" on line 514. Is this something page should support? I'm depending on it for tests. Thank you!

**Comment by shuvalov-anton** [comment]
What you want to get on server environment when you require `page`?

**Comment by shuvalov-anton** [comment]
It's kinda strange to add `document &&` and `window &&` everywhere. Have we more simple way?

**Comment by ryanatkn** [comment]
I agree it's strange to add `document` and `window` checks throughout the code like [this pull request](https://github.com/visionmedia/page.js/pull/241) does. My use case just needs page.js to be required without throwing an error. The first reply to that PR suggests bailing out of the module early if the browser globals aren't detected. Another option is to just fix the two lines that break at the top level scope of the module that were added in 1.6.2. 

To maximum flexibility (like allowing access to certain constructors and methods by user test code, many of which already work fine outside the browser) you'd want page.js to initialize properly and not bail out. Your call though. :)

The two instances that break are `document` on line 20 and `window` on line 514. (because it's in an IIFE)

**Comment by jamesalley** [comment]
+1. We are using Page in an isomorphic app and get the same error.

**Comment by shuvalov-anton** [comment]
closed with #256. I'm going to release `1.6.3` on weekends
