### ISSUE TITLE
Support IE 8 and IE9

### ISSUE THREAD

**Issue by gubagu** [visionmedia/page.js#259]
Hey there,

First great routing plugin !
I am using it for a SPA that should work client side in IE8+ but i came across unsolvable problem.
The routing does not seem to work in IE8 and IE9.
In IE8 added a polyfill for add/removeEventListener and the HTML5-History-API it load the first page but the rest of the routes do not trigger page.js at all and it render a blank url does not exist browser page.
In IE9 with HTML5-History-API every time i try to navigate to another route it adds the hash tag (and it is supposed to) but because of that the urls render page not found. The whole SPA is client side. I am serving it with nginx.
Has anyone came across this problem? Any help highly appreciated. Thanks in advance !

Cheerz,
Guby

**Comment by 74io** [comment]
Me neither. Can't get it to work in IE9. Any pointers or tips as to how the latest released has changed and which polyfills are required? I hope so as its an excellent router.

**Comment by gubagu** [comment]
I tested also the example pages with HTML5-History-API under IE9 also do not work. Did something change? Because the page.js is supposed to support IE8+ ?
By the way IE8 does not have addEventListener nor removeEventListener page.js is relying on.
Is that new ?

**Comment by amitava82** [comment]
Same issue here. It triggers "*" route handler

**Comment by paulocoghi** [comment]
You probably have already done this, but just to be sure, did you create the .htaccess file (and in case of nginx the correspondent config rule)?

```
<ifModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !index
    RewriteRule (.*) index.html [L]
</ifModule>
```

**Comment by tjyrkinen** [comment]
@amitava82 Thanks a lot! Went the monkey-patch route on it for a quick fix and saved hours of debugging time there. Fixed navigation issues on IE9 for me for now.

**Comment by dinkelburt** [comment]
+1
Looked at #288 and after applying the changes locally, it fixed the issue for me. Would like to see it merged.

**Comment by jliuhtonen** [comment]
It is no use adding `html5-history-api` polyfill, because this breaks IE9 compatibility because IE9 does not provide the initial slash in `.pathname`. Please merge.

**Comment by matthewp** [comment]
I'm going to close, as far as I know these browsers are still supported. Maybe someone fixed it without updating this issue.
