### ISSUE TITLE
Map route path to callback after calling page.start();

### ISSUE THREAD

**Issue by jonathanamartin** [visionmedia/page.js#270]
Very nice looking router.  It looks like it has everything I'm looking for.  The only quesiton I have is around dynamically adding routes.

I have a need to map path's to additional callbacks after the page.start() function has been invoked.  Is this supported?

Would I just call page.start() again?

**Comment by shuvalov-anton** [comment]
Only if added routes related to current url.

**Comment by jonathanamartin** [comment]
Ah okay.  Thanks for the info.
