### ISSUE TITLE
htaccess example

### ISSUE THREAD

**Issue by mourtazag** [visionmedia/page.js#277]
Hello everybody,

I'm discovering page.js and I'm having fun with. 
I would like to know if someone could give an example of .htaccess file. I would like to handle direct url ! 

Thanks everyone !
Mourtaza.

**Comment by michaelphipps** [comment]
I know this is old, but something like this works:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.html [QSA,L]
```

**Comment by paulocoghi** [comment]
Done in PR #453 . This can be closed ;)

**Comment by matthewp** [comment]
Yay!
