### ISSUE TITLE
Some newbie questions

### ISSUE THREAD

**Issue by dukedougal** [visionmedia/page.js#283]
I have added page into a fairly ordinary HTML template purchased from Themeforest.

The HTML template has links on the menu that slide open other menus, but with page installed they seem to have stopped working.  Can you suggest why this might be happening?

Also, how do I tell page that I want a link to behave like a normal HTML link and send a request instead of it being handled by page?

thanks!

**Comment by matthewp** [comment]
You might be using a wildcard route? `page('*', function() { ... })`. If you only add routes for things you *do* want to be handled by page.js then other links should work. 

```js
page('/this-should-be-handled, function(){

});
```

Let me know if this doesn't answer your question and I'll try my best to help. :)
