### ISSUE TITLE
Navigating to custom route.

### ISSUE THREAD

**Issue by PaulHMason** [visionmedia/page.js#285]
This is probably a stupid question, but I can't figure it out.

I've set up a web application with a bunch of routes, e.g.

http://localhost/subfolder/#!/home
http://localhost/subfolder/#!/one
http://localhost/subfolder/#!/two
http://localhost/subfolder/#!/three

The first (home) is mapped to the root url. If I try to navigate to http://localhost/subfolder/#!/two directly in a new browser window it always directs to the root. Any idea how to get it to go the the specified root directly?

The back/forward buttons on the browser don't work either for navigating between routes.
Thanks

**Comment by matthewp** [comment]
Do you have some example code of how you are using page.js with these routes?

**Comment by matthewp** [comment]
We've recently fixed some issues with hashbang support that I suspect might fix these issues. Happy to reopen if you are still having problems though. Thanks!
