### ISSUE TITLE
hash causes page reload

### ISSUE THREAD

**Issue by ccorcos** [visionmedia/page.js#289]
I have a route like this: `'/profile/:id'`

And when I go from the first href to the second, theres a page reload and I have no idea why.

```
href="/profile/11/?q=world"
href="/profile/11/#sort"
```

**Comment by efyx** [comment]
As a workaround you can add ` <base href="">`  to your ` <head>`  this looks to fix the issue (source https://github.com/visionmedia/page.js/issues/220 )
