### ISSUE TITLE
Callback is fired before URL got changed

### ISSUE THREAD

**Issue by nsisodiya** [visionmedia/page.js#295]
I was using Davis router library, I tried page.js, there i noticed a strange thing. My route callback are being fired before the url change.
Let me explain, 
I have a route called `/user/345`
now, let support, I am page `/team` , I clicked on url link ( `/user?id=345`), when I click this link, my module got loaded. When my module loads, it needs id  (Ex `345`) - so, I am extracting id from page url, like `window.location.pathname`. but that is not working because, when my module loads, by that time my url is still `/team`. 
So, currently I am handling using setTimeout

``` js
page("/user/:id", () =>{
window.setTimeout(()=>{
     ModuleLoader();
}, 0)
})
```

Any better solution ??

**Comment by wereHamster** [comment]
Use `ctx.params.id` instead of reading `window.location`.

**Comment by matthewp** [comment]
Yep, @wereHamster has the answer here.
