### ISSUE TITLE
Get "upcoming" pathname in .exit()

### ISSUE THREAD

**Issue by bensmeets** [visionmedia/page.js#298]
I use transitions to go from A to B. When entering B, i have a global variable hacked in, that stores the previous page's pathname. I would like to do the same for .exit() as well. 

E.g., When going from A to B, I want everything animating to the left, when going from B to A, i want everything going from right to left. So I need to be able to read the next page's pathname in an exit handler of a route.

Is that even possible?

Cheers.

**Comment by ascii-husky** [comment]
I think page.current is the new route

**Comment by rerdos** [comment]
I can confirm, that `page.current` is the new (next) route.

**Comment by matthewp** [comment]
Maybe we should document this?

**Comment by bensmeets** [comment]
Sorry cor ghe late response. But to handle thie situation correctly, you would need to have both the current and previous page at the samentime, right? If like above ‘current’ is the ne t page, then what would be the ‘previous’ page?
