### ISSUE TITLE
Readme's Context chapter never mentions "params"

### ISSUE THREAD

**Issue by ronkorving** [visionmedia/page.js#300]
Was looking for how to extract variables from routes, and took a while to find it. I think params should probably be explained in the Context chapter.

**Comment by woodlandhunter** [comment]
There's a section:

https://github.com/visionmedia/page.js#working-with-parameters-and-contexts

Is this not what you are referring to?

**Comment by ronkorving** [comment]
You're right. I think I was going top-to-bottom, not taking the time to read all the docs, and what I needed wasn't at the place I was reading (lazy...). Anyway, it is documented, so I'll close this.
