### ISSUE TITLE
Not able to do routing properly in page.js

### ISSUE THREAD

**Issue by iiison** [visionmedia/page.js#302]
I am using page.js for routing in a Single Page Application. For testing purpose, I am using `npm http-server`.

I am not able to do routing. I am not sure what I am missing. following is my code:

index.html:

``` html
<html>
<head>
  <title>test page!</title>
  <script src="/js/libs/page.js"></script>
</head>
<body>
  this is body of test
  <a href="/test">Simple test</a>

  <script type="text/javascript" src="/js/routes.js"></script>
</body>
</html>
```

routes.js

``` javascript
function initRoutes () {
  var testRoutes = {
    test : function (context, next) {
      alert("testing");

      if(next){
        next();
      }
    },
    test2 : function (context, next) {
      alert("I am jon snow, I know nothing.");
    }
  };
  page.base('/');

  page('/', testRoutes.test);
  page('/test', testRoutes.test2);
  page('/two-args', testRoutes.test, testRoutes.test2);
  page();
}
initRoutes();
```

from my `http-server`, I am accessing `http://0.0.0.0:8081`. I am getting an test as `alert`, but I am not getting the `alert` for route `http://0.0.0.0:8081/test`.

I am not sure what I am missing. Please let me know if you need anything else.

**Comment by shuvalov-anton** [comment]
@iiison you need remove `page.base('/')` from your code.

**Comment by iiison** [comment]
@shuvalov-anton yes, I figured that out. but I am still not sure when should I use page.base('/').

Could you please help me with that.

**Comment by axelpale** [comment]
@iiison If you look at page's source, the base path is plainly added in front of paths without any checking. The result is probably equal to `page('//test', testRoutes.test2)` with the default base.

**To answer your question:** you should not use `page.base('/')`.

Maybe the implementation of `page.base` should strip all trailing slashes.

This issue can be closed, I think.

**Comment by matthewp** [comment]
Thanks!
