### ISSUE TITLE
Wildcard route navigation issues

### ISSUE THREAD

**Issue by ryanscherler** [visionmedia/page.js#305]
It seems with wildcard routes that the page state will not change when navigating to another wildcard route URL.

Example route definition: 

```
page('/admin/pages/:page(.*), loadRoute())
```

If I click on a link: /admin/pages/about/our-services - this correctly loads the route (the first time coming from another location)

If I then click on another similar route wildcard link such as: /admin/pages/contact/request-documentation - the URL changes, but not the content.

Is there a way to 'force' a page change for wildcard routes?

**Comment by ChrisC** [comment]
I've been able to work around this by calling `next` if the window hasn't reloaded by checking the value of `init` in the context argument. Calling `next` this way seems to force the page change with the latest path available from the context... not ideal, but working for now....

```
page('/admin/pages/*', function(context, next) {
  if (!context.init) return next();
 loadRoute();
}
```
