### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by gertsonderby** [visionmedia/page.js#315]
I note with some worry the increasing number of issues and PRs on this project, and low maintenance activity. What is the status of the project, in terms of activity? Can we expect to see it return to active maintenance in the foreseeable future?

**Comment by shuvalov-anton** [comment]
Hi @gertsonderby! Now I have lack of time to support the project. But next one problem is I don't write so many code now and especially SPA things with pagejs. Mb in near future I will return to maintenance. If you want to cleanup issues and to review pull requests in the project you are welcome :D Just ping me

**Comment by woodlandhunter** [comment]
@shuvalov-anton 

I would be willing to tag issues, make minor fixes/doc corrections, things of that nature.

Can we at the very least do a new release to incorporate the newest version of path-to-regexp (1.2.1)? This version restores the previous wildcard behavior and as such will close a handful of related issues (preventing new ones as well I don't doubt).

**Comment by shuvalov-anton** [comment]
@woodlandhunter Looks good to me. Can you make a patch w/ path-to-regexp 1.2.1?

**Comment by woodlandhunter** [comment]
Yes, see #323

Thanks.

**Comment by jorgecasar** [comment]
I'm having some issues using this project with Polymer, we made a routing component wrapping pagejs. @shuvalov-anton I can help you with the maintenance if you want, because we are doing a hard use of the library.

**Comment by shuvalov-anton** [comment]
@jorgecasar Thank you! You're strongly welcome :D Just ping me, when you want to merge something. Be respect with tests and commit rules.

**Comment by woodlandhunter** [comment]
@shuvalov-anton can we get this release pushed to npm ? Is there something else I can do to help with this?

**Comment by shuvalov-anton** [comment]
@woodlandhunter Just I should publish it. I can do it tomorrow. If you want to help you can update `history.md` and test it. // cc @gertsonderby

**Comment by gertsonderby** [comment]
I asked the original question because I myself don't really have time to devote to maintenance of this project - I'm tied up in several others at this point. I'm very happy that others do, however, and in future I may also be able to. For now, however, I can't.

**Comment by woodlandhunter** [comment]
@shuvalov-anton Added #325 to update `History.md` and fixed the only existing test that hit the wildcard routes. Let me know if I can do anything else.

**Comment by shuvalov-anton** [comment]
@woodlandhunter i'm going to release 1.6.4 today.

**Comment by woodlandhunter** [comment]
Great! After that I will go through the open issues that pertain to wildcard routes.

**Comment by shuvalov-anton** [comment]
@woodlandhunter `page@1.6.4` landed on npm :D

**Comment by matthewp** [comment]
The project was unmaintained for a long time, but I am maintaining it now! Yay! page.js is going to start getting a lot better, I promise :)
