### ISSUE TITLE
Page sometimes appending an additional slash?

### ISSUE THREAD

**Issue by quirkles** [visionmedia/page.js#332]
Hi, so my routing setup looks like this:

``` javascript
    page('/login', function () {
      // render the login page
      console.log(page.current);
    });
    page('/home', function () {
      // render my home page
      console.log(page.current);
    });
    page('*', function () {
      console.log(page.current);
      // catchall
    });
    page.start({
      hashbang: true
    });
```

If I use `page('/home')` in my code, no problems

if i just enter http://mysite.com/#!/home then i hit the catchall callback and the value of page.current is `'//home'` with two slashes, if i just hit enter in the address bar again then it hits the `'/home'` callback, as expected.

So what gives? what am I doing wrong

**Comment by farzher** [comment]
+1

Editing the URL in your browser manually breaks in the same way for me too.

**Comment by Dashed** [comment]
I'm running into the same issue. Looks like this PR fixes this: https://github.com/visionmedia/page.js/pull/322

**Comment by farzher** [comment]
I stopped using `hashbang`, it's too buggy. There's an issue about removing it #229
I just use `page.base('/#')` instead (personally I don't even want to bang anyway)

**Comment by quirkles** [comment]
Interesting, yeah I implemented my own work around where I catch 404's and see if they are equal to '/'  plus an existing route. Very ugly but Necessary until this gets fixed.

**Comment by Dashed** [comment]
@farzher ah sweet. `page.base('/#')` seems to good workaround. Thanks.

**Comment by quirkles** [comment]
Gonna try that too.

**Comment by farzher** [comment]
You could even put `page.base('/#!')` if you really wanted :)

**Comment by matthewp** [comment]
I believe this has been fixed by a recent version. I was unable to create it upon trying. Please try yourself using 1.8.0 and let me know if it's still an issue. Thanks!
