### ISSUE TITLE
Authentication & redirecy

### ISSUE THREAD

**Issue by santosborom** [visionmedia/page.js#334]
Question: are there examples of how to perform authentication and route to another page after login success?

**Comment by tsongas** [comment]
Did you ever find anything?

**Comment by matthewp** [comment]
Performing authentication is not within the realm of page.js, but I am assuming you are able to figure that part out yourself. If so it is something like:

```js
page('/login', function(){

  document.querySelector('form').addEventListener('submit', function(ev){
    ev.preventDefault();

    // This is up to you!
    doAuthentication().then(function(){
      page.redirect('/');
    });
  });

});
```
