### ISSUE TITLE
why do you write "tiny" router? it's huge!

### ISSUE THREAD

**Issue by yairEO** [visionmedia/page.js#336]
That's a TON of code for such a simple thing.
tiny is [this](http://krasimirtsonev.com/blog/article/A-modern-JavaScript-router-in-100-lines-history-api-pushState-hash-url)

That's a **complete** false advertising. comparing to what a simple thing it does, your code isn't tiny, it's medium/large

**Comment by woodlandhunter** [comment]
Is it huge or medium?

**Comment by yairEO** [comment]
it's not **tiny** for sure :/

**Comment by rstacruz** [comment]
It was at some point :)
