### ISSUE TITLE
Redirect behaves differently when coming from outside website

### ISSUE THREAD

**Issue by Giggiux** [visionmedia/page.js#337]
When inside the website (i.e. the browser is on a page of the website) a URL of the form `<webisteAddress>/#!<route>` will redirect properly (when typed in the address bar), while a URL of the form `<webisteAddress>/#!/<route>` will not.
When outside the website (i.e. in a new tab) a URL of the form `<webisteAddress>/#!/<route>` will redirect correctly, while the form `<webisteAddress>/#!<route>` will not.
Essentially a form of the URL is valid only inside the website, while the other only outside of it, when manually inserting the address in the browser address bar.

**Comment by mavroskardia** [comment]
This behavior is still present in the version of page.js included in the Polymer Starter Kit (v.1.2.3).

You can replicate per Giggiux's instructions with the PSK out-of-the-box.

**Comment by matthewp** [comment]
Thanks @Giggiux, but I don't quite understand what you mean by "inside of the website", can you clarify?

**Comment by matthewp** [comment]
I'm going to close for now. Will reopen if we can get a better idea of what the problem is. Thanks!

**Comment by Giggiux** [comment]
Sorry for late answer:
With "inside the site" I mean when you are browsing it. While "outside" is while you try to access it from another webpage (of another domain/subdomain) by link or copy-pasting the link.

**Comment by matthewp** [comment]
Ok, thanks for responding. I'll reopen and think more about this

**Comment by paulocoghi** [comment]
@Giggiux , Since many improvements have been made since the day you opened this issue, including enhancements in hash-based navigation, could you test again? Thanks!

**Comment by Giggiux** [comment]
@paulocoghi if the API didn't change, I could test it with the same WebApp I was developing 2 years ago just changing page.js' version, is this the case?

If the API changed, It may take a while to find some time to do it :S.

**Comment by matthewp** [comment]
@Giggiux If you are using a 1.x version, then the API has not changed.
