### ISSUE TITLE
Internet explorer pushstae not working with hashtag

### ISSUE THREAD

**Issue by harilalinapp** [visionmedia/page.js#340]
I have been using requirejs for the application with page.js for routing. But hasgtags not working in internet explorer.  I have installe html5 polyfill as mentioned by readme. BUt no use. The popstate is not firing am using ie10. The following is the code i have been using for routing.
page('*', function(ctx) {

})

page();

**Comment by mrova** [comment]
Same here, any thoughts/updates?

**Comment by mrova** [comment]
Looks like only IE10 supporting popstate event:
https://developer.mozilla.org/en-US/docs/Web/Events/popstate

I solved my problem using hashchange:
https://developer.mozilla.org/en-US/docs/Web/Events/hashchange

**Comment by iliketomatoes** [comment]
I have the same scenario as @harilalinapp and the history back button is not working on any browser if I just change hashtags.
