### ISSUE TITLE
Suggestion: Option to replace '#!' with just '#'?

### ISSUE THREAD

**Issue by LoveAndHappiness** [visionmedia/page.js#344]
I believe there is currently no choice to change the hashbang to just a hash.

I believe that the hashbang makes url links slightly less attractive. Is there a reason you guys chose hashbang instead of hash?

**Comment by Dashed** [comment]
@LoveAndHappiness just fyi, this is a workaround that works for me: https://github.com/visionmedia/page.js/issues/332#issuecomment-166701658

**Comment by dantman** [comment]
@LoveAndHappiness `#foo` already has the native browser implications of jumping to whatever element has `id="foo"`; `#!` is an often used pattern for when the fragment is instead used for state that JS acts on instead of an id for the browser to jump to.

**Comment by matthewp** [comment]
Yeah, use of `#!` is standard for client side routers. With @dantman point we'll stick with how it is.
