### ISSUE TITLE
Please cut a 1.6.5 release

### ISSUE THREAD

**Issue by jpodwys** [visionmedia/page.js#360]
The page.js master branch currently contains a fix for shadow dom that I need in my production application. I have forked page.js into my company's private account because I don't like being unpinned with any dependencies. However, I would prefer to use an official page.js release. Thanks!

**Comment by ChadKillingsworth** [comment]
I'd also like a release. I'm using github as a CDN for npm installs, but would just prefer a new release.

**Comment by rstacruz** [comment]
hmm... let's see what we can do about that.

**Comment by rstacruz** [comment]
1.7.0 is out with the recent fixes on master. thanks for reporting!

https://github.com/visionmedia/page.js/blob/master/History.md

**Comment by jpodwys** [comment]
Thanks very much for the fast work!

**Comment by uwolfer** [comment]
The fix for shadow DOM seems not to be included in this release. It got reverted just in the release commit: https://github.com/visionmedia/page.js/commit/00899e6c0c0b7e45b1f1962709c58b91ceec9812#diff-50e3e6872ec225cd4caa566f1f15e89cL552

Can you please release a follow-up fix release?
