### ISSUE TITLE
Executing next(err) doesn't allow us to render an error page

### ISSUE THREAD

**Issue by jdrydn** [visionmedia/page.js#364]
When executing middlewares, if an error was encountered how come we can't use `next(err)` in node-fashion?

```
page(function (ctx, next) {
  if (!ctx.user) {
    return next(new Error('User not found'));
  }

  // Continue with the middleware function
});
```

I'm surprised this isn't adopted, it could lead to excellent error-page handling in Page.JS. Something like:

```
page(function (err, ctx, next) {
  // Render error page
});
```

**Comment by paulocoghi** [comment]
@jdrydn Unfortunately page.js is [not being maintained](https://github.com/visionmedia/page.js/issues/384) anymore.
