### ISSUE TITLE
when hash doesn't change, the callback function shouldn't be called

### ISSUE THREAD

**Issue by iamwelk** [visionmedia/page.js#366]
here is my page options

``` javascript
page({
    hashbang: true
});
```

when I click the link which is same with current URL, the function bind to the URL will be called even if the URL has not changed. I think it's should be configured.
Wish your reply. Thank you~

**Comment by iandunn** [comment]
It seems like this is a duplicate of #417 

(This is older, but #417 has more discussion, including a workaround)

**Comment by matthewp** [comment]
Thanks @iandunn! Let's discuss in #477
