### ISSUE TITLE
page.js with webpack HMR (hot module replacement)

### ISSUE THREAD

**Issue by timaschew** [visionmedia/page.js#371]
Just wanted to share my solution which looks simple but took so much time to figure out why it was not working. So the tricky part for me was `page.callbacks = []`

Put your page.js setup into a file like **app.js** and export the page instance.
In your webpack entry point you need this:

``` js
let page = require('./app')
if (module.hot) {
  module.hot.accept('./app', function() {
    page.stop()
    page.callbacks = []
    page = require('./app')
  })
}
```

**Comment by timaschew** [comment]
Oh, maybe I missed some other things to reset.
I think it would be nice if the page.js would provide some kind of a `.reset()` function so that the user don't need to know all the internal stuff which need to be reset.

**Comment by tractorcow** [comment]
I'm a developer writing applications which must conform to semantic versioning. Can someone please confirm whether the above code is going to continue working in non-major releases of page.js, or should I consider `page.callbacks` as non-public API that is subject to change without notice? :D

**Comment by tractorcow** [comment]
Also, did you notice what the other effects were? I can have a look on your behalf, @timaschew , since I'll need to solve these problems as well. :D

**Comment by mogita** [comment]
I'm using @timaschew 's method and it just works.
As for @tractorcow 's question, I can't confirm because I'm using the npm release. As far as I `console.log`, the page.js instance still includes the `callbacks` property.

**Comment by matthewp** [comment]
@tractorcow you can consider `page.callbacks` as public for at least 1.x.

**Comment by tractorcow** [comment]
Thanks @matthewp :D
