### ISSUE TITLE
Handle Locale-based URLs

### ISSUE THREAD

**Issue by ramendezb** [visionmedia/page.js#379]
Hey guys, I was wondering if you have setup this library for switching from one locale to the other. Ideally I want to create a site in which any defined URL can work adding the locale string right after the domain, for example: domain.co/en/rest/of/url

**Comment by bvalyou** [comment]
Bit late for your question, but maybe you should just have each path prefixed with `:locale`. In your example, `/:locale/rest/of/url` would map to your example.

**Comment by paulocoghi** [comment]
Excellent suggestion.

**Comment by matthewp** [comment]
Thanks @bvalyou for the answer!
