### ISSUE TITLE
page reload after clicking anchor

### ISSUE THREAD

**Issue by tomhuynen** [visionmedia/page.js#383]
Hi,

It seems that the page refreshes after adding an anchor hash to the end of the url. 
IE: mysite.com/#test 

Possible cause:

In page.js line 335 the current and canonical path are compared like this:

`current === ctx.canonicalPath`

The current is composed like this:

`current = location.pathname + location.search;`

It works again when I add the `location.hash`:

`current = location.pathname + location.search + location.hash;`

Regards,

Tom

**Comment by matthewp** [comment]
Hey @tomhuynen, sorry for the long time without a reply. I tried changing the hash in one of the examples and I didn't see the problem that you are reporting here. Here's what I get:

![change-hash2](https://user-images.githubusercontent.com/361671/34917003-864993ce-f90e-11e7-8c7b-172cb0fa8d53.gif)


Can you provide more information on what causes this bug? Is it a specific browser version?

Going to close for now, happy to reopen if we can get more info to make it reproducible.
