### ISSUE TITLE
Not being maintained?

### ISSUE THREAD

**Issue by agauniyal** [visionmedia/page.js#384]
There are tons of pull requests being piled up and a lot of issues are unanswered here. Is this code abandoned or still being developed?

**Comment by fega** [comment]
this is so sad, page.js has a great potential.

**Comment by MrCsabaToth** [comment]
I like that it's relatively minimalistic: solves a lot of tasks in the routing realm but don't force you into other stuff

**Comment by A** [comment]
Guys, if you want to maintain pagejs you can ask TJ to share the access with you.

**Comment by MrCsabaToth** [comment]
Unfortunately I'm way too busy to pick this up :(

**Comment by agauniyal** [comment]
I don't think I'm qualified enough to maintain this project at the moment but I'm willing to help with any other tasks. About finding a good maintainer, I would suggest putting up a notice on top of README.md and posting the project to /r/programming, news.ycombinator.com and/or similar sites. This is such a great project that should definitely live on 👍

**Comment by fega** [comment]
Yeah, im not qualified too.
I like @agauniyal solution

**Comment by paulocoghi** [comment]
Everyone here in this thread is much more qualified than me.

So, here is a suggestion: a new **team of contributors**, not only one.

@tj , do you mind to allow everyone in this thread to form a "council" and help to maintain the project, giving the proper repo permissions?

**Comment by Shyam-Chen** [comment]
I want to rewrite it for ES modules support.

```js
import page, { redirect, show, start, stop, base, exit, exit } from 'page';
```

**Comment by Shyam-Chen** [comment]
I will rewrite it for ES modules support. [TODO](https://github.com/Shyam-Chen/Web-Starter-Kit/blob/master/src/scripts/luyou/index.js)

**Comment by tj** [comment]
Yeah I'm cool with adding anyone who wants to maintain

**Comment by rstacruz** [comment]
page.js has a few maintainers on board, but I think most of us have moved on from using page.js to other alternatives. sorry :(

**Comment by paulocoghi** [comment]
Or maybe [Rich-Harris/roadtrip](https://github.com/Rich-Harris/roadtrip)

**Comment by aldebaran798** [comment]
I found https://github.com/camelaissani/frontexpress but seems that is not intended for SPA, i like because is express like

**Comment by kshep92** [comment]
Reading this thread and a tear comes to my eye. It would be a crying shame if this project were to die; it's so darn useful its agnosticism is so attractive! @rstacruz what alternatives have you move on to, if I my ask for a recommendation?

**Comment by rstacruz** [comment]
As previously mentioned in the thread, these work great:

- https://www.npmjs.com/package/riot-route (very similar to page.js in API)
- https://www.npmjs.com/package/roadtrip (has support for transitions & enter/leave handlers)

**Comment by kshep92** [comment]
Thanks much!

**Comment by rogeriotaques** [comment]
@tj are u still maintaining this project?

**Comment by tj** [comment]
nope

**Comment by matthewp** [comment]
@tj I'm willing to maintain this.

**Comment by matthewp** [comment]
Hello everyone, I've become the new maintainer of page.js! Want to let everyone know that page.js is going to continue to be simple and will largely remain the same as it is today, just with bugs fixed and pull requests merged. That said, I do have some ideas to make simple but powerful changes in the future.

The direction I'll be taken is to:

1. Triage issues and pull requests. Get as many closed as possible!
2. Make sure we have versions out on a regular basis.
3. Clean the repo up a little bit as there are some outdated things (like bower), this will come in a future major release.
4. Possible explore fixing some of the stranger parts of the API and come up with new feature. One thing I think would be cool is some how producing observables when that comes out ([here's an issue about it in whatwg/dom](https://github.com/whatwg/dom/issues/544)). Imagine if you could do something like `page.on('/user/:id').map(params => ({ page: 'user', id: params.id }))` and pass that around?

With almost 100 issues and 50 pull requests __(1)__ is going to take me quite a long time. But I'm hoping eventually to convince people who have left page.js to come check it out again!

**Comment by matthewp** [comment]
Going to close as this isn't an issue any more ;)

@tj or @rstacruz, can you give me npm permissions? `npm owner add matthewp page`. Thanks!
