### ISSUE TITLE
google seo anyone?

### ISSUE THREAD

**Issue by coderofsalvation** [visionmedia/page.js#387]
Anyone can confirm that google (indexing) succesfully triggers page.js-powered anchortags?
In other words: does google index/render page.js-applications correctly?

**Comment by Grynn** [comment]
tl;dr Nope; Google will not crawl page.js sites well. 

If you are writing a web-site as opposed to a web-app, it is better to do server side rendering and send only rendered content. You'd be better of with a classic CMS (Wordpress) instead. But if you're making an app (esp. one where login is required) page.js is awesome.

**Comment by pbuzdin** [comment]
https://plus.google.com/u/0/+JohnMueller/posts/LT4fU7kFB8W

**Comment by coderofsalvation** [comment]
update: It seems google tries to do everything to index javascript-ish website. SPA's using page.js seems a good approach.
