### ISSUE TITLE
Is '/' relative to 'options.base' or 'document.location.href'?

### ISSUE THREAD

**Issue by luozhihua** [visionmedia/page.js#395]
``` html

document.location.href === 'xxx.com/ui/profile/details';

<a id="homepage" href="/homepage">homepage</a>

<script>
page.base('/ui');
page.start({
    click: true
});
</script>
```

when i click the link#homepage, browser location.href is changed to `/homepage`, my question is I set `page.base` to `/ui`, why link is not relative to `page.base`;

**Comment by paulocoghi** [comment]
`page.base( 'ui' )` inform that all your app's routes will be inside `yourdomain.com/ui/...`

It doesn't insert `ui` automatically in your links.

All you have to do is to add `ui` in links by yourself:

```
<a id="homepage" href="/ui/homepage">homepage</a>
```

**Comment by matthewp** [comment]
Thanks for answering!
