### ISSUE TITLE
How redirect page without change the URL?

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [visionmedia/page.js#399]
How can I redirect to HTML file ?

is there any special method do return a HTML file like ```Express```?

```javascript
page('/login', function (ctx, next) {
   //show login.html and keep the url /login
}

page('/contacts', function (ctx, next) {
   //show contacts.html and keep the url /contacts
}

page.start();
```

**Comment by paulocoghi** [comment]
The purpose of page.js is to deal only with routes.

To decide which HTML file to load and render it, you will need an additional tool, mainly a front-end framework, like [Ractive](http://www.ractivejs.org/), [Vue](https://vuejs.org/), [React](https://facebook.github.io/react/), [Angular](https://angular.io/), etc.

**Comment by rodrigorodriguescosta** [comment]
OK, thank you

**Comment by paulocoghi** [comment]
I develop a framework ( https://github.com/Altiva/altiva ) to deal with this more easily, but it's in alpha version and doesn't have a documentation yet.

It's very simple to determine which HTML files need to be loaded for each route, and it's based on Ractive.

If you like it, you can learn Ractive as well to use more advanced features in each HTML component.

**Comment by paulocoghi** [comment]
If you want you can also post issues in Portuguese and/or Brazilian Portuguese on Altiva issues.

**Comment by matthewp** [comment]
Thanks for answering!
