### ISSUE TITLE
page.js not working with history back or forward

### ISSUE THREAD

**Issue by Nomia** [visionmedia/page.js#405]
Hi, I've used page.js in my project for about a week. Sometimes, page.js will not work with `history.back()`. The issue is that, when I hit the back button(or manually call history.back) on chrome, the url will change, but the callback doesn't get called. (the URL changes but the route isn't triggered again).

And the history.forward or the forward button on my chrome or any other browser will not trigger the router callback.

I don't know whether it's a problem in my code, I found someone has the same issue with me, not solved.

**Comment by Nomia** [comment]
@paulocoghi could u help me out?

**Comment by paulocoghi** [comment]
Are registering page's popstate / click bindings with:

```javascript
page()
```

**Comment by Nomia** [comment]
yes

**Comment by Nomia** [comment]
@paulocoghi  here is my code: 
```
Page({
        hashbang: true,

        click: false
});
```

**Comment by paulocoghi** [comment]
I've seen other users with problems with hashbang mode, with which I am not familiar.

I always used page.js without hashbang mode.

**Comment by Nomia** [comment]
Oh, bad news. I have to use hashbang mode, coz it will be hosted natively(file:///).

thanks anyway.

**Comment by paulocoghi** [comment]
Now I understand better your scenario and I have good news. You are not obligated to use hashbang, even when using file:///

All you have to do in this case is:

```javascript
// Staring routing system with automatic environment discovery, mobile or desktop
if( window && ( window.cordova || window.location.protocol == 'file:' ) )
{
	page( { dispatch: false } )
	page( '/' ) // Choose the route to be loaded first
}
else
{
	page()
}
```

**Comment by paulocoghi** [comment]
Do not use `click: false` or hashbang.

**Comment by Nomia** [comment]
Thx for ur advice @paulocoghi , I'll give it a shot and feedback here.

**Comment by paulocoghi** [comment]
Any news?

**Comment by ankit90anand** [comment]
You can mentiom popstate:true in configuration of page.

**Comment by Nomia** [comment]
Sorry for the late feedback. I've handled the history back and forward problem manually in my project before @paulocoghi 's suggestion. Lots of work was in a rush. I'll test the suggested solution once I've got time. Feel free to close this issue.

**Comment by WesleyDRobinson** [comment]
perhaps an issue with bfcache: https://developer.mozilla.org/en-US/Firefox/Releases/1.5/Using_Firefox_1.5_caching

Adding a [`pageshow` event](https://developer.mozilla.org/en-US/docs/Web/Events/pageshow) handler resolves:
```
window.onpageshow = event => {
    if (event.persisted) window.location.reload()
}
```

**Comment by paulocoghi** [comment]
@matthewp , without an response from the OP, I am in favor of closing the issue. If this problem does exist, we need at least one example code in which it occurs in order to work on the case.

**Comment by matthewp** [comment]
That's fair, let's close. Happy to reopen if we get more info!

**Comment by kyle-west** [comment]
I am experiencing this too. I have multiple apps mounted at different paths of the same domain. (i.e: `/foo` is a different express app than `/bar`) Some apps use `PageJS` for client-side routing, others do not. When I navigate from an app that uses page to another that does not, and then use the back button to return to the previous app's page, I am experiencing the same behavior.

**Comment by kyle-west** [comment]
It turns out that adding 
```html
<script>
  window.addEventListener('popstate', (e) => {
    if (e.state && e.state.path) {
      window.location.href = e.state.path;
    }
  });
</script>
```
to the file that does not use PageJS solved the problem for me.

**Comment by paulocoghi** [comment]
Thanks for sharing your solution!

Since it is external to PageJS, maybe we can add this to the README
