### ISSUE TITLE
Page.js triggered on call to diferent domain

### ISSUE THREAD

**Issue by cristiancs** [visionmedia/page.js#407]
If i have a website example.com and have a link to example.com.co the page.js trigger is executed.

**Comment by paulocoghi** [comment]
Can you post the code you are using?

The correct behavior is not to interfere with links to different domains.

**Comment by cristiancs** [comment]
```
page('/:first/:second/:page',goBack);
page('/:first/:second',goBack)

function goBack(ctx,next){
	
		if(!actual.called){
			actual.called = true;
			actual.first = ctx.params.first;
			actual.second = ctx.params.second;
		}
		else{
			console.log(ctx);
			window.location.href = ctx.path;
		}
```
		
		
	}
Actually i only do this code to fix another bug (when clicking go back on the browser it doesn't work).

The code works well when you link to example.ru by example, but if it is .com.ru its trigger page.js.

**Comment by matthewp** [comment]
Thanks, this is an interesting one, I'll try to take a look at it soon.

**Comment by paulocoghi** [comment]
Excellent!
