### ISSUE TITLE
Using a query string in combination with base fails to dispatch to root

### ISSUE THREAD

**Issue by shangaslammi** [visionmedia/page.js#41]
The following code demonstrates the problem

```
page.base('/example')
page.page('/', function() { console.log("example root"); })

page('/example')  // works OK
page('/example?foo=bar')  // does not find the route
```

I traced it back to this line in `Context` initialization

```
this.path = path.replace(base, '') || '/';
```

Without a query string, `path` is correctly initialized to "/", but if the base is followed by a query string, the result of replace is not empty.

I managed to work around this in my application by changing `pathname` initialization in `Route.prototype.match` to

```
pathname = ~qsIndex ? path.slice(0, qsIndex) || '/' : path
```

but I'm not sure if this is the correct way to fix this.

**Comment by matthewp** [comment]
I just checked and this issue doesn't exist any more. 7 years is a long time for a bug! Closing.
