### ISSUE TITLE
Could you please update NPM version

### ISSUE THREAD

**Issue by PaulMaly** [visionmedia/page.js#411]

**Comment by paulocoghi** [comment]
I'm not qualified to maintain page.js but, if @tj doesn't mind sharing the repository's access with me, I can help with pull-requests and not-so-complex issues.

**Comment by paulocoghi** [comment]
More details in https://github.com/visionmedia/page.js/issues/384 (_"Not being maintained"_)

**Comment by Shyam-Chen** [comment]
@paulocoghi I would like to create a new repository for it and provide ES modules.

**Comment by matthewp** [comment]
page.js is being maintained now. I will update the npm package as soon as I get permissions there.

**Comment by PaulMaly** [comment]
Very good news, man! I'm happy, thanks!

**Comment by tj** [comment]
@matthewp should hopefully have npm access now!

**Comment by matthewp** [comment]
@tj I do indeed, thanks!

**Comment by matthewp** [comment]
Releases are happening regularly, check the releases page for more information: https://github.com/visionmedia/page.js/releases
