### ISSUE TITLE
Issue: appending multiple query param to url

### ISSUE THREAD

**Issue by longS2baobao** [visionmedia/page.js#412]
page.js line 167.
var url = (hashbang && ~location.hash.indexOf('#!')) ? **location.hash.substr(2) + location.search** : location.pathname + location.search + location.hash;

I'm having problem with the above highlighted part. It keeps pending query string to the end of my url. I'm not sure if this is a bug.

**Input:**
https://localhost:8551/?s=1

**Processing code:**
  const defaultRoute = 'MYPAGE'
  page('/', () => {
    page.redirect(defaultRoute);
  });
  page(defaultRoute, () => {});
  page.start({ hashbang: true, dispatch: true, popstate: false });

**Output:**
First time:         https://localhost:8551/?s=1#!MYPAGE
After refresh:    https://localhost:8551/?s=1#!MYPAGE?s=1
Refresh again:   https://localhost:8551/?s=1#!MYPAGE?s=1?s=1

**Comment by matthewp** [comment]
This doesn't appear to be an issue any more. Closing.

![screen shot 2018-01-18 at 6 48 55 am](https://user-images.githubusercontent.com/361671/35096839-aa1d1e78-fc1b-11e7-9e98-e6fef20553ec.png)

**Comment by matthewp** [comment]
Oops, closed the wrong issue :P

**Comment by matthewp** [comment]
I just tested and this does not occur any more. Only get the one query string as part of the URL.

**Comment by S2-** [comment]
Somehow this happens again in latest master: https://i.vgy.me/h0ytkR.webm
