### ISSUE TITLE
How to use pushState to set url with page.js api?

### ISSUE THREAD

**Issue by dman777** [visionmedia/page.js#420]
How can I use page.js api's to set the pushState so that I can set the url query params without reloading the page? 

The below works on initial page load with `/search-listings` but after that, I can not get the url to change with pushState:

```javaScript
page('/search-listings', function(context) {
  window.history.pushState(null, null, '/search-listings?foo=bar')
  console.log('aaaaa'); 
  app.route = 'search-listings';
});
```

**Comment by paulocoghi** [comment]
You do not need to call the `pushState` function because page.js already does this automatically.

**Comment by paulocoghi** [comment]
@matthewp , this can be closed ;)

**Comment by matthewp** [comment]
There's also page.replace which we should probably document...

**Comment by matthewp** [comment]
Yep, thanks!
