### ISSUE TITLE
QUESTION: anyone can explain this

### ISSUE THREAD

**Issue by vickenliu** [visionmedia/page.js#424]
Hi , 
from the project's examples, if i hit this url `http://localhost:4000/server/contact`, the backend returns the related html, and when the browser renders the html, is page.js also do the front-end routing like here it knows to show the contact view, not the default index. 
thanks for explaination.

**Comment by matthewp** [comment]
Yes, that's right, when page.js first loads it will start by loading the route that is represented by the current URL. Hope that answers your question! :)
