### ISSUE TITLE
How to use page.js?

### ISSUE THREAD

**Issue by Hillel-Nagid** [visionmedia/page.js#425]
this code not working:
`page('/create-account_1', function(){
  $( "#video" ).load("../videos.html #create-account_1");
})
page('*', function(){
  document.body.innerHTML= "Hi"
})
`
![image](https://user-images.githubusercontent.com/24993843/30786704-02644456-a183-11e7-84f5-71489d5681cc.png)
![image](https://user-images.githubusercontent.com/24993843/30786708-0f4c7e54-a183-11e7-8116-c8f3003c9a27.png)

**Comment by UtsavPreet** [comment]
Did you set the base url to 'freelancer-ninja' ?
And you called the page function right ?

**Comment by matthewp** [comment]
Yup, what @UtsavPreet said. Can you respond @Hillel-Nagid?

**Comment by matthewp** [comment]
Going to close for now since there wasn't a response. Let us know if there is anything else you need :)
