### ISSUE TITLE
Is there a way to load partials example without node app (only using the browser stack)?

### ISSUE THREAD

**Issue by pr3ssh** [visionmedia/page.js#449]

**Comment by matthewp** [comment]
https://github.com/visionmedia/page.js/pull/450 updates the example so that it works with a normal http server. However, refreshing the browser will not work without server-side routes. See https://github.com/visionmedia/page.js/issues/373 for discussion about that.

**Comment by matthewp** [comment]
Closed by #450

**Comment by pr3ssh** [comment]
@matthewp thx!
