### ISSUE TITLE
unsafe-eval error

### ISSUE THREAD

**Issue by bradmarder** [visionmedia/page.js#458]
`var hasProcess = new Function('return typeof process')() !== 'undefined';`

The above line of code triggers an `unsafe-eval` error (if a content security policy is set).

Is there a way to rewrite that line without having to `eval` it?

**Comment by matthewp** [comment]
Oh, arg, I didn't think about csp. Luckily we are getting rid of that eval in https://github.com/visionmedia/page.js/pull/454. So I'll try to get that worked out soon.

**Comment by matthewp** [comment]
This is fixed in https://github.com/visionmedia/page.js/releases/tag/1.8.3. Thanks for filing!
