### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by RenaudParis** [visionmedia/page.js#468]
[This package](https://www.jsdelivr.com/package/npm/page) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by matthewp** [comment]
Yeah, I suppose so, i'm surprised this was never there before.

**Comment by RenaudParis** [comment]
Hi @paulocoghi !

I'm sorry for the preformatted issue comment earlier, it is created automatically by jsDeliver and I did not feeel like modifying it because I didn't know anyrthing intelligent to add :)

Thank you for being so reactive, it is impressive! And great, because I will be able to centralize all my external libs using jsDeliver now :) :) :)

Thanks again!

**Comment by matthewp** [comment]
This was released in 1.8.4, thanks @paulocoghi!

**Comment by RenaudParis** [comment]
Thanks @matthewp !

**Comment by RenaudParis** [comment]
Hi guyz!

Is it possible to add the minified version to the repo?
jsDeliver seems to be unable to provide me with the page/page.min.js file.
Or is it a bug with jsDeliver?

When I check the default file in jsDeliver, this is what happens:
![image](https://user-images.githubusercontent.com/676896/36953140-ae1e5a02-2018-11e8-96f1-c09dbf721025.png)

Please advise (whenever you have the time, this is clearly not pressing matters)

Thank you all :)

**Comment by paulocoghi** [comment]
Thanks for the note, Renaud!

@matthewp , unlike CDN JS, jsDelivr does not provide minified versions automatically. If you want, I set up Rollup to do this.

**Comment by matthewp** [comment]
Yeah that's cool with me.

**Comment by RenaudParis** [comment]
@paulocoghi @matthewp to be noted that jsDeliver does support automatic minification (as I read in a github issue comment somewhere), so I can load `npm/page@1.8.4/page.min.js` instead of just `npm/page@1.8.4`.

However, I can't seem to find how to automate this process (of adding the minified file name to the "require") using their website, which makes it painful if I am to change my dependencies every so often.

That's why I still think it could be great to have a minified version of page.js already inside the repo, as you planned to do.

Let me know what you think!

Cheers,
