### ISSUE TITLE
Minified JS Not Available

### ISSUE THREAD

**Issue by aluferraz** [visionmedia/page.js#471]
Hi !

I'm trying to download the minified version from the CDN, but it returns a 404..

Is it available anywhere else?

**Comment by paulocoghi** [comment]
@aluferraz , sorry for the inconvenience. It's currently unavailable.

@matthewp , I am a little busy today but, if you want, I can configure Rollup to generate the minified version, too.

**Comment by matthewp** [comment]
Did we ever have a minified version? I thought that we just relied on cdnjs which makes those automatically. https://cdnjs.cloudflare.com/ajax/libs/page.js/1.8.4/page.min.js

**Comment by paulocoghi** [comment]
Strangely the minified version was not available when I tried to access it. Perhaps CDN JS had not yet completed the process. :) xD

In this case, there is no need to do anything on our side.

**Comment by RenaudParis** [comment]
@aluferraz see issue #468 , the team seems to be working on the generation of a minified file inside the repo, which will allow us to download it seemlessly from any CDN out there :1st_place_medal: :+1: Kudos to them!

**Comment by matthewp** [comment]
So I guess just a temporary glitch? https://cdnjs.cloudflare.com/ajax/libs/page.js/1.10.0/page.min.js working now. Closing...
