### ISSUE TITLE
v1.8.5 is actually v1.8.3

### ISSUE THREAD

**Issue by nick-woodward** [visionmedia/page.js#476]
### Description

It looks like an older version of `page.js` was published to NPM.

A quick way of validating this is to either pull down the package from NPM 
or look at the source via [unpkg](https://unpkg.com/page@1.8.5/page.js).

The change in question that I'm looking for is @dthorne's fix for `page.js` within shadow dom (#469).

**Comment by nick-woodward** [comment]
Upon further inspection it looks like v1.8.5 on `cdnjs` is using an old version of `page.js` as well.

**Comment by nick-woodward** [comment]
I stand corrected even further, it looks like v1.8.5 doesn't even have the latest version of the code built on GitHub.

So v1.8.5 is literally the same as v1.8.3 (since that's the last time page.js was built) on every platform.

**Comment by matthewp** [comment]
Weird, I'm releasing a new version anyways.

**Comment by matthewp** [comment]
I just released 1.8.6....
