### ISSUE TITLE
hashbang and file:// protocol problem

### ISSUE THREAD

**Issue by PaulMaly** [visionmedia/page.js#492]
When onclick event fired, we've got situation then handler **never** handle navigation, because this condition is always true:

```javascript
if (pageBase && orig === path) return;
```

How to fix that?

**Comment by PaulMaly** [comment]
Also, **pathname** includes absolute path to the file, but seems should be a relative path.

**Comment by kaisermann** [comment]
I'm also needing to get hashbang and `file://` working with regular `<a href></a>` links.

Does this makes sense? 

```js
if (pageBase && orig === path && (!isLocation || this._window.location.protocol !== 'file:')) {
  return;
}
```

**Comment by matthewp** [comment]
I'm not sure I understand the situation to be honest. If you could create an HTML file that I can drop into a browser with the file protocol I can dive into it.

**Comment by kaisermann** [comment]
Based on the `basic` example: 

```html
<!DOCTYPE html>
<html>
  <head>
	<title>page: hashbang + file: protocol issue</title>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/page.js/1.10.2/page.js"></script>
  </head>
  <body>
  	<p></p>
    <ul>
      <li><a href="./">/</a></li>
      <li><a href="./about">/about</a></li>
    </ul>

    <script>
      page('/', index);
      page('/about', about);

      page.start({ hashbang: true });

      function index() {
        document.querySelector('p')
          .textContent = 'viewing index';
      }
      function about() {
        document.querySelector('p')
          .textContent = 'viewing about';
      }
    </script>
  </body>
</html>
```

With file protocol:
![file](https://user-images.githubusercontent.com/12702016/46367465-051ae000-c654-11e8-8de2-d9276a000fd3.gif)


with http protocol:
![http](https://user-images.githubusercontent.com/12702016/46367467-06e4a380-c654-11e8-8aa3-1af6298b7d97.gif)

**Comment by kaisermann** [comment]
@PaulMaly Sure, no problem! However, I'm not sure if this is really the right way of fixing it. @matthewp any thoughts?

**Comment by kaisermann** [comment]
@matthewp I think this can be closed now :grin:

**Comment by PaulMaly** [comment]
Yep, thank you!
