### ISSUE TITLE
onpopstate doesn't include query string when e.state = null

### ISSUE THREAD

**Issue by cj-idoctours** [visionmedia/page.js#495]
When e.state = null (like when clicking on a link that is the same as the current location except with a hash), the query parameters were not added to page.show()

This problem occurs on line 998 on page.js

Problem code:
        998 page.show(loc.pathname + loc.hash, undefined, undefined, false);

Fix:
        998  page.show(location.pathname + location.search + location.hash, undefined, undefined, false);

**Comment by matthewp** [comment]
This is a bit of a tough one to test.
