### ISSUE TITLE
Support redirection?

### ISSUE THREAD

**Issue by ericfong** [visionmedia/page.js#50]
Currently, I want to redirect to a default url by

page('/default', function(context, next){
  // show but quickly back to /
})
page('/', function(context, next){
  // redirect to '/default'
  page('/default');
})
page();

I think the problem come from 

page.replace = function(path, state, init, dispatch){
    var ctx = new Context(path, state);
    ctx.init = init;
    if (null == dispatch) dispatch = true;
    if (dispatch) page.dispatch(ctx);
    ctx.save();
    return ctx;
  };

which do     ctx.save();  before page.dispatch

Shall we save ctx first?

**Comment by shuvalov-anton** [comment]
closed with #140
