### ISSUE TITLE
npm doesn't install the current version (1.11.4)

### ISSUE THREAD

**Issue by tazomazo** [visionmedia/page.js#544]
It looks like an older version of page.js was published to NPM.

Please check!

**Comment by matthewp** [comment]
Looks right to me:

```bash
> npm dist-tag ls page
latest: 1.11.4
```

**Comment by tazomazo** [comment]
Looks right BUT it has differences to the version I can download directly from Gitub.

For example: the fix for #535 is missing.

**Comment by matthewp** [comment]
Ah, need to do a release then. Ok, will try to do so tomorrow.

**Comment by matthewp** [comment]
1.11.5 is on npm now: https://github.com/visionmedia/page.js/releases/tag/v1.11.5
