### ISSUE TITLE
What NPM Package should I use? "page" or "page.js"

### ISSUE THREAD

**Issue by MrAmericanMike** [visionmedia/page.js#583]
Sorry if this was asked already, but I can't find a clear difference, and I don't understand why or how both NPM packages end up pointing to the same repository even when they install different libraries.

https://www.npmjs.com/package/page

https://www.npmjs.com/package/page.js

The second one mentions it's a fork, however it link to the exact same repository, so that got me confuse. I see it mentions it uses path-to-regex and other than that is useless.

**Comment by matthewp** [comment]
`page` is the official package.
