### ISSUE TITLE
Redirect from '/' to '/Home' gets reset on Context#save()

### ISSUE THREAD

**Issue by Industrial** [visionmedia/page.js#94]
Hi.

I have two routes, '/' and '/:title'. In the '/' route I want to redirect to '/Home' but this instantly gets reset back to '/'.

``` js
page('/', function() {
  console.log('index!');
  page('/Home');
});
page('/:title', function() {
  console.log('titled page!');
});
page();
```

When I run this, I think because of https://github.com/visionmedia/page.js/blob/master/index.js#L145, my output is 'index!' and 'titled page!' but I see '/Home' in the URL for a split second and then the URL is '/' again.

Putting the page('/Home'); in a setTimeout 0 'fixes' it, but i'd rather not. I'm making a small wiki app, so I want to redirect to a page named Home instantly. How do I achieve this behaviour?

**Comment by matthewp** [comment]
I think this use-case is served by redirects: https://github.com/visionmedia/page.js#pagefrompath-topath

Going to close, happy to reopen if I'm misunderstanding the need.
